import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/common/Header";
// import { Navigation } from "@/components/common/Navigation";
import { getCryptoRates } from "@/lib/crypto"; // Import the data fetching function

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const initialCryptoData = await getCryptoRates(); // Fetch data on the server

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header initialData={initialCryptoData} /> {/* Pass data to the header */}
        {/* <Navigation /> */}
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
